# Generated by Django 4.1.2 on 2023-03-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_ingrediente_imagen_categoria_imagen'),
        ('pedidos', '0002_remove_itempedido_subtotal_remove_pedido_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
