# Generated by Django 4.1.2 on 2023-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_listo',
            field=models.DateTimeField(blank=True),
        ),
    ]
