# Generated by Django 4.1.2 on 2023-03-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_pedido_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='pedidos', to='pedidos.itempedido'),
        ),
    ]
