# Generated by Django 4.1.2 on 2023-03-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_remove_pedido_items_remove_pedido_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
