# Generated by Django 4.1.2 on 2023-03-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nombre',
        ),
    ]
