# Generated by Django 4.1.2 on 2023-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_remove_pedido_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
