# Generated by Django 4.1.2 on 2023-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_ingrediente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
